# Pull image from the osrf
FROM ros:graphical_with_user
# Manually compile and install GTSAM
#RUN wget https://research.cc.gatech.edu/borg/sites/edu.borg/files/downloads/gtsam-3.2.1.tgz && \
#  tar xzf gtsam-3.2.1.tgz && \
#  rm gtsam-3.2.1.tgz && \
#  cd gtsam-3.2.1 && \
#  mkdir build && \
#  cd build && \
#  cmake .. && \
#  make install

# Install some additional packages
#RUN \
#  apt-get update && \
#  apt-get install -y \
#    vim \
#  && \
#  rm -rf /var/lib/apt/lists/*
